version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: nosql_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: protein_db

  neo4j:
    image: neo4j:5
    container_name: nosql_neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"   # interface web
      - "7687:7687"   # bolt
    environment:
      NEO4J_AUTH: "neo4j/password"   # login: neo4j / mdp: password
      NEO4J_PLUGINS: '["apoc"]'
    volumes:
      - ./data/neo4j/data:/data
      - ./data/neo4j/plugins:/plugins
      - ./data/neo4j/import:/var/lib/neo4j/import

  # tu pourras ajouter ton app Python plus tard ici
  # app:
  #   build: ./app
  #   container_name: nosql_app
  #   depends_on:
  #     - mongo
  #     - neo4j
  #   environment:
  #     MONGO_URI: "mongodb://mongo:27017"
  #     NEO4J_URI: "bolt://neo4j:7687"
  #     NEO4J_USER: "neo4j"
  #     NEO4J_PASSWORD: "password"
