services:
  mongo:
    image: mongo:7
    container_name: nosql_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: protein_db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.adminCommand('ping')\" || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20


  neo4j:
    image: neo4j:5
    container_name: nosql_neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"   # interface web
      - "7687:7687"   # bolt
    environment:
      NEO4J_AUTH: "neo4j/password"   # login: neo4j / mdp: password
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_dbms_security_procedures_unrestricted: "gds.*,apoc.*"
      NEO4J_dbms_security_procedures_allowlist: "gds.*,apoc.*"
      NEO4J_server_memory_heap_initial__size: "1500M"  # Ajusté à 2G pour éviter de surcharger si laptop
      NEO4J_server_memory_heap_max__size: "1500M"
      NEO4J_dbms_memory_pagecache_size: "512M"
    volumes:
      - ./data/neo4j/data:/data
      - ./data/neo4j/plugins:/plugins
      - ./data/neo4j/import:/var/lib/neo4j/import
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 120s

  app:
    build: ./app           
    container_name: nosql_app
    restart: "no"
    depends_on:
      mongo:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    environment:
      MONGO_URI: "mongodb://mongo:27017"
      NEO4J_URI: "bolt://neo4j:7687"
      NEO4J_USER: "neo4j"
      NEO4J_PASSWORD: "password"
      FLASK_APP: app.py       # Utile pour Flask
      FLASK_DEBUG: "1"        # Mode debug pour voir les erreurs
    ports:
      - "5000:5000"        
    volumes:
      - ./app:/app           
      - ./data:/app/data